before_install: yarn global add greenkeeper-lockfile@1
before_script:  greenkeeper-lockfile-update
after_script:   greenkeeper-lockfile-upload
matrix:
  include:
  - os:         osx
    osx_image:  xcode9.2
    language:   node_js
    node_js:    '10'

cache:
  yarn:         true
  directories:
  - node_modules
script:
- yarn bootstrap
- lerna run yarn build

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
